
name: a1_s08_needs

on:
  workflow_dispatch:

jobs:
  impl1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "ok"


  impl2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "ok"
